from fpdf import FPDF
name = input("Enter your full name: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
summary = input("Enter a short summary about yourself: ")
education = input("Enter your education details: ")
skills = input("Enter your skills (comma-separated): ")
experience = input("Enter your work experience: ")
pdf = FPDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(200, 10, txt=name, ln=True, align='C')
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 10, f"Email: {email}\nPhone:{phone}\n\nSummary:\n{summary}\n\nEducation:\n{education}\n\nSkills:\n{skills}\n\nExperience:\n{experience}")
pdf.output("resume.pdf")